create table albums
(
    album_id     INT
        primary key,
    album_name   VARCHAR(255),
    album_type   VARCHAR(255),
    tracks       INT,
    genre        VARCHAR(255),
    release_year YEAR,
    duration     TIME
);


INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (1, 'The Grateful Dead', 'Studio', 9, 'San Francisco sound', 1967, '0:34:53');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (2, 'Anthem of the Sun', 'Studio', 5, 'Acid', 1968, '0:38:57');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (3, 'Aoxomoxoa', 'Studio', 8, 'Acid', 1969, '0:36:00');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (4, 'Live/Dead', 'Contemporary live', 7, 'Acid', 1969, '1:15:07');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (5, 'Workingman''s Dead', 'Studio', 8, 'Folk', 1970, '00:35:33');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (6, 'American Beauty', 'Studio', 10, 'Folk', 1970, '00:42:21');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (7, 'Skull and Roses', 'Contemporary live', 11, 'Jam', 1971, '00:72:12');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (8, 'Europe ''72', 'Contemporary live', 17, 'Jam', 1972, '1:49:35');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (9, 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Contemporary live', 7, 'Jam', 1973, '0:47:28');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (10, 'Wake of the Flood', 'Studio', 7, 'Jazz', 1973, '0:45:34');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (11, 'From the Mars Hotel', 'Studio', 8, 'Psychedelic', 1974, '0:37:26');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (12, 'Blues for Allah', 'Studio', 11, 'Jazz', 1975, '0:44:13');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (13, 'Steal Your Face', 'Contemporary live', 14, 'Jam', 1976, '01:24:13');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (14, 'Terrapin Station', 'Studio', 5, 'Progressive', 1977, '0:35:38');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (15, 'Shakedown Street', 'Studio', 10, 'Pop', 1978, '0:39:04');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (16, 'Go to Heaven', 'Studio', 9, 'Blues', 1980, '0:38:19');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (17, 'Reckoning', 'Contemporary live', 16, 'Folk', 1981, '1:12:21');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (18, 'Dead Set', 'Contemporary live', 15, 'Jam', 1981, '1:13:51');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (19, 'In the Dark', 'Studio', 7, 'Blues', 1987, '0:40:37');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (20, 'Dylan & the Dead', 'Contemporary live', 7, 'Gospel', 1989, '0:43:23');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (21, 'Built to Last', 'Studio', 9, 'Pop', 1989, '0:49:52');
INSERT INTO albums (album_id, album_name, album_type, tracks, genre, release_year, duration) VALUES (22, 'Without a Net', 'Contemporary live', 14, 'Jam', 1990, '2:11:56');


create table songs
(
    song_id      INT
        primary key,
    song_name    VARCHAR(255),
    album        VARCHAR(255)
        references albums,
    genre        VARCHAR(255),
    writer       VARCHAR(255),
    lead_singer  VARCHAR(255),
    release_year INT,
    duration     TIME,
    keyboardist  VARCHAR(255)
);


INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (1, 'The Golden Road (To Unlimited Devotion)', 'The Grateful Dead', 'San Franciso Sound', 'Grateful Dead', 'Jerry Garcia', 1967, '02:07', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (2, 'Beat It On Down the Line', 'The Grateful Dead', 'Country-blues', 'Jesse Fuller', 'Bob Weir', 1967, '02:27', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (3, 'Good Morning, Little School Girl', 'The Grateful Dead', 'Blues', 'Sonny Boy Williamson', 'Ron "Pigpen" McKernan', 1967, '05:56', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (4, 'Cold Rain and Snow', 'The Grateful Dead', 'Folk', 'Obray Ramsey', 'Jerry Garcia', 1967, '02:25', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (5, 'Sitting on Top of the World', 'The Grateful Dead', 'Country-blues', 'Lonnie Chatmon, Walter Vinson', 'Jerry Garcia', 1967, '02:01', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (6, 'Cream Puff War', 'The Grateful Dead', 'San Franciso Sound', 'Jerry Garcia', 'Jerry Garcia', 1967, '02:25', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (7, 'Morning Dew', 'The Grateful Dead', 'Folk', 'Bonnie Dobson, Tim Rose', 'Jerry Garcia', 1967, '05:00', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (8, 'New, New Minglewood Blues', 'The Grateful Dead', 'Blues', 'Noah Lewis', 'Bob Weir', 1967, '02:31', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (9, 'Viola Lee Blues', 'The Grateful Dead', 'Blues', 'Noah Lewis', 'Jerry Garcia, Bob Weir', 1967, '10:01', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (10, 'That''s It for the Other One', 'Anthem of the Sun', 'Acid ', 'Grateful Dead', 'Jerry Garcia, Bob Weir', 1968, '07:40', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (11, 'New Potato Caboose', 'Anthem of the Sun', 'Acid ', 'Phil Lesh, Robert Hunter', 'Bob Weir', 1968, '08:26', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (12, 'Born Cross-Eyed', 'Anthem of the Sun', 'Acid ', 'Bob Weir', 'Bob Weir', 1968, '02:04', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (13, 'Allligator', 'Anthem of the Sun', 'Acid ', 'Phil Lesh, Ron "Pigpen" McKernan, Robert Hunter', 'Ron "Pigpen" McKernan', 1968, '11:20', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (14, 'Caution (Do Not Stop on Tracks)', 'Anthem of the Sun', 'Acid ', 'Grateful Dead', 'Ron "Pigpen" McKernan', 1968, '09:37', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (15, 'St. Stephen', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter, Phil Lesh', 'Jerry Garcia', 1969, '04:26', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (16, 'Dupree''s Diamond Blues', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '03:32', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (17, 'Rosemary', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '01:58', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (18, 'Doin'' That Rag', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '04:41', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (19, 'Mountains of the Moon', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '04:02', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (20, 'China Cat Sunflower', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '03:40', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (21, 'What''s Become of the Baby', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '08:12', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (22, 'Cosmic Charlie', 'Aoxomoxoa', 'Acid ', 'Jerry Garcia, Robert Hunter', 'NULL', 1969, '05:29', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (23, 'Dark Star', 'Live/Dead', 'Acid ', 'Grateful Dead, Robert Hunter', 'NULL', 1969, '23:18', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (24, 'St. Stephen', 'Live/Dead', 'Acid ', 'Jerry Garcia, Robert Hunter, Phil Lesh', 'NULL', 1969, '06:31', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (25, 'The Eleven', 'Live/Dead', 'Acid ', 'Robert Hunter, Phil Lesh', 'NULL', 1969, '09:18', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (26, 'Turn On Your Love Light', 'Live/Dead', 'Acid ', 'Deadric Malone, Joseph Scott', 'NULL', 1969, '15:05', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (27, 'Death Don''t Have No Mercy', 'Live/Dead', 'Acid ', 'Reverend Gary Davis', 'NULL', 1969, '10:28', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (28, 'Feedback', 'Live/Dead', 'Acid ', 'Grateful Dead', 'NULL', 1969, '07:49', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (29, 'And We Bid You Goodnight', 'Live/Dead', 'Acid ', 'Grateful Dead', 'NULL', 1969, '0:35', 'Tom Constanten');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (30, 'Uncle John''s Band', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia, Bob Weir, Phil Lesh', 1970, '04:42', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (31, 'High Time', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '05:13', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (32, 'Dire Wolf', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '03:13', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (33, 'New Speedway Boogie', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '04:05', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (34, 'Cumberland Blues', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter, Phil Lesh', 'Jerry Garcia, Bob Weir, Phil Lesh', 1970, '03:15', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (35, 'Black Peter', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '05:42', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (36, 'Easy Wind', 'Workingman''s Dead', 'Folk', 'Robert Hunter ', 'Ron "Pigpen" McKernan', 1970, '04:59', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (37, 'Casey  Jones', 'Workingman''s Dead', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '04:24', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (38, 'Box of Rain', 'American Beauty', 'Folk', 'Phil Lesh, Robert Hunter', 'Phil Lesh', 1970, '05:18', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (39, 'Friend of the Devil', 'American Beauty', 'Folk', 'Jerry Garcia, John Dawson, Robert Hunter', 'Jerry Garcia', 1970, '03:24', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (40, 'Sugar Magnolia', 'American Beauty', 'Folk', 'Bob Weir, Rob Hunter', 'Bob Weir', 1970, '03:19', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (41, 'Operator', 'American Beauty', 'Folk', 'Ron "Pigpen" McKernan', 'Ron "Pigpen" McKernan', 1970, '02:25', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (42, 'Candyman', 'American Beauty', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '06:14', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (43, 'Ripple', 'American Beauty', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '04:09', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (44, 'Brokedown Palace', 'American Beauty', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1970, '04:09', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (45, 'Till the Morning Comes', 'American Beauty', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia, Bob Weir, Phil Lesh', 1970, '03:08', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (46, 'Attics of My Life', 'American Beauty', 'Folk', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia, Bob Weir, Phil Lesh', 1970, '05:12', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (47, 'Truckin''', 'American Beauty', 'Folk', 'Grateful Dead, Robert Hunter', 'Bob Weir', 1970, '05:03', 'Other');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (48, 'Bertha', 'Skull and Roses', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1971, '05:27', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (49, 'Mama Tried', 'Skull and Roses', 'Jam', 'Merle Haggard', 'NULL', 1971, '02:42', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (50, 'Big Railroad Blues', 'Skull and Roses', 'Jam', 'Noah Lewis', 'NULL', 1971, '03:34', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (51, 'Playing in the Band', 'Skull and Roses', 'Jam', 'Bob Weir, Rob Hunter', 'NULL', 1971, '04:39', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (52, 'The Other One', 'Skull and Roses', 'Jam', 'Grateful Dead', 'NULL', 1971, '18:05', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (53, 'Me and My Uncle', 'Skull and Roses', 'Jam', 'John Phillips', 'NULL', 1971, '03:06', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (54, 'Big Boss Man', 'Skull and Roses', 'Jam', 'Luther Dixon, Al Smith', 'NULL', 1971, '05:12', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (55, 'Me and Bobby McGee', 'Skull and Roses', 'Jam', 'Fred Foster, Kris Kristofferson', 'NULL', 1971, '05:43', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (56, 'Johnny B. Goode', 'Skull and Roses', 'Jam', 'Chuck Berry', 'NULL', 1971, '03:42', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (57, 'Wharf Rat', 'Skull and Roses', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1971, '08:31', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (58, 'Not Fade Away/Goin'' Down the Road Feeling Bad', 'Skull and Roses', 'Jam', 'Buddy Holly, Norman Petty', 'NULL', 1971, '09:14', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (59, 'Cumberland Blues', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter, Phil Lesh', 'Jerry Garcia, Bob Weir', 1972, '05:47', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (60, 'He''s Gone', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1972, '07:12', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (61, 'One More Saturday Night', 'Europe ''72', 'Jam', 'Bob Weir', 'Bob Weir', 1972, '04:45', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (62, 'Jack Straw', 'Europe ''72', 'Jam', 'Bob Weir, Rob Hunter', 'Jerry Garcia, Bob Weir', 1972, '04:46', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (63, 'You Win Again', 'Europe ''72', 'Jam', 'Hank Williams', 'Jerry Garcia', 1972, '03:54', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (64, 'China Cat Sunflower', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1972, '05:33', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (65, 'I Know You Rider', 'Europe ''72', 'Jam', 'Traditional', 'Jerry Garcia, Bob Weir, Phil Lesh', 1972, '04:55', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (66, 'Brown-Eyed Women', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1972, '04:55', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (67, 'Hurts Me Too', 'Europe ''72', 'Jam', 'Elmore James, Marshall Sehorn', 'Ron "Pigpen" McKernan', 1972, '07:18', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (68, 'Ramble On Rose', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1972, '06:09', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (69, 'Sugar Magnolia', 'Europe ''72', 'Jam', 'Bob Weir, Rob Hunter', 'Bob Weir', 1972, '07:04', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (70, 'Mr. Charlie', 'Europe ''72', 'Jam', 'Robert Hunter, Ron "Pigpen" McKernan', 'Ron "Pigpen" McKernan', 1972, '03:40', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (71, 'Tennessee Jed', 'Europe ''72', 'Jam', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1972, '07:13', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (72, 'Truckin''', 'Europe ''72', 'Jam', 'Jerry Garcia, Bob Weir, Robert Hunter, Phil Lesh', 'Bob Weir, Jerry Garcia, Phil Lesh', 1972, '13:08', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (73, 'Epilogue', 'Europe ''72', 'Jam', 'Grateful Dead', 'Instrumental', 1972, '04:33', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (74, 'Prelude', 'Europe ''72', 'Jam', 'Grateful Dead', 'Instrumental', 1972, '08:08', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (75, 'Morning Dew', 'Europe ''72', 'Jam', 'Bonnie Dobson, Tim Rose', 'Jerry Garcia', 1972, '10:35', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (76, 'Katie Mae', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Lightnin'' Hopkins', 'NULL', 1973, '04:46', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (77, 'Dark Hollow', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Bill Browning', 'NULL', 1973, '03:30', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (78, 'I''ve Been All Around This World', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Traditional', 'NULL', 1973, '04:40', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (79, 'Wake Up Little Susie', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Felice Bryant, Boudleaux Bryant', 'NULL', 1973, '02:40', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (80, 'Black Peter', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1973, '07:20', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (81, 'Smokestack Lightning', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Howlin'' Wolf', 'NULL', 1973, '18:00', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (82, 'Hard to Handle', 'History of the Grateful Dead, Volume One (Bear''s Choice)', 'Jam', 'Al Bell, Allen Jones, Otis Redding', 'NULL', 1973, '06:14', 'Ron "Pigpen" McKernan');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (83, 'Mississippi Half-Step Uptown Toodeloo', 'Wake of the Flood', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1973, '05:42', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (84, 'Let Me Sing Your Blues Away', 'Wake of the Flood', 'Jazz', 'Keith Godchaux, Robert Hunter', 'Keith Godchaux', 1973, '03:15', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (85, 'Row Jimmy ', 'Wake of the Flood', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1973, '07:11', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (86, 'Stella Blue ', 'Wake of the Flood', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1973, '06:22', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (87, 'Here Comes the Sunshine', 'Wake of the Flood', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1973, '04:37', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (88, 'Eyes of the World', 'Wake of the Flood', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1973, '05:16', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (89, 'Weather Report Suite', 'Wake of the Flood', 'Jazz', 'Eric Andersen, John Perry Barlow, Bob Weir', 'Bob Weir', 1973, '12:41', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (90, 'U.S. Blues', 'From the Mars Hotel', 'Psychedelic', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1974, '04:37', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (91, 'China Doll', 'From the Mars Hotel', 'Psychedelic', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1974, '04:09', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (92, 'Unbroken Chain', 'From the Mars Hotel', 'Psychedelic', 'Phil Lesh, Robert Petersen', 'Phil Lesh', 1974, '06:45', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (93, 'Loose Lucy', 'From the Mars Hotel', 'Psychedelic', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1974, '03:23', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (94, 'Scarlet Begonias', 'From the Mars Hotel', 'Psychedelic', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia, Donna Godchaux', 1974, '04:19', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (95, 'Pride of Cucamonga', 'From the Mars Hotel', 'Psychedelic', 'Phil Lesh, Robert Petersen', 'Phil Lesh', 1974, '04:16', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (96, 'Money Money', 'From the Mars Hotel', 'Psychedelic', 'Bob Weir, John Perry Barlow', 'Bob Weir', 1974, '04:21', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (97, 'Ship of Fools', 'From the Mars Hotel', 'Psychedelic', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1974, '05:22', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (98, 'Hekp on the Way', 'Blues for Allah', 'Jazz', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1975, '03:15', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (99, 'Slipknot!', 'Blues for Allah', 'Jazz', 'Grateful Dead', 'Instrumental', 1975, '04:03', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (100, 'Franklin''s Tower', 'Blues for Allah', 'Jazz', 'Jerry Garcia, Bill Kreutzmann, Robert Hunter', 'Jery Garcia', 1975, '04:32', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (101, 'King Solomon''s Marbles', 'Blues for Allah', 'Jazz', 'Phil Lesh', 'Instrumental', 1975, '01:55', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (102, 'Stronger than Dirt or Milkin'' the Turkey', 'Blues for Allah', 'Jazz', 'Mickey Hart, Bill Kreutxmann, Phil Lesh', 'Instrumental', 1975, '03:25', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (103, 'The Music Never Stopped', 'Blues for Allah', 'Jazz', 'John Perry Barlow, Bob Weir', 'Bob Weir, Donna Godchaux', 1975, '04:35', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (104, 'Crazy Fingers', 'Blues for Allah', 'Jazz', 'Jery Garcia, Robert Hunter', 'Jerry Garcia', 1975, '06:41', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (105, 'Sage & Spirit', 'Blues for Allah', 'Jazz', 'Bob Weir', 'Instrumental', 1975, '03:07', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (106, 'Blues for Allah', 'Blues for Allah', 'Jazz', 'Jery Garcia, Robert Hunter', 'Jerry Garcia, Donna Godchaux, Keith Godchaux, Bob Weir', 1975, '03:21', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (107, 'Sand Castles & Glass Camels', 'Blues for Allah', 'Jazz', 'Grateful Dead', 'Instrumental', 1975, '05:24', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (108, 'Unusual Occurrences in the Desert', 'Blues for Allah', 'Jazz', 'Jery Garcia, Robert Hunter', 'Jerry Garcia, Donna Godchaux, Keith Godchaux, Bob Weir', 1975, '03:48', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (109, 'Promised Land', 'Steal Your Face', 'Jam', 'Chuck Berry', 'NULL', 1976, '03:15', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (110, 'Cold Rain and Snow', 'Steal Your Face', 'Jam', 'Grateful Dead', 'NULL', 1976, '05:35', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (111, 'Around and Around', 'Steal Your Face', 'Jam', 'Chuck Berry', 'NULL', 1976, '05:07', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (112, 'Stella Blue ', 'Steal Your Face', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1976, '08:48', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (113, 'Mississippi Half-Step Uptown Toodeloo', 'Steal Your Face', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1976, '08:00', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (114, 'Ship of Fools', 'Steal Your Face', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1976, '06:59', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (115, 'Beat It On Down the Line', 'Steal Your Face', 'Jam', 'Jesse Fuller', 'NULL', 1976, '03:22', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (116, 'Big River', 'Steal Your Face', 'Jam', 'Johnny Jash', 'NULL', 1976, '04:53', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (117, 'Black-Throated Wind', 'Steal Your Face', 'Jam', 'John Perry Barlow, Bob Weir', 'NULL', 1976, '06:05', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (118, 'U.S. Blues', 'Steal Your Face', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1976, '05:18', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (119, 'El Paso', 'Steal Your Face', 'Jam', 'Marty Robbins', 'NULL', 1976, '04:15', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (120, 'Sugaree', 'Steal Your Face', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1976, '07:33', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (121, 'It Must Have Been the Roses', 'Steal Your Face', 'Jam', 'Robert Hunter', 'NULL', 1976, '05:58', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (122, 'Casey Jones', 'Steal Your Face', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1976, '07:02', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (123, 'Estimated Prophet', 'Terrapin Station', 'Progressive', 'John Perry Barlow, Bob Weir', 'Bob Weir', 1977, '05:35', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (124, 'Dancin'' in the Streets', 'Terrapin Station', 'Progressive', 'William Stevenson, Marvin Gaye, I.J. Hunter', 'Bob Weir, Donna Godchaux', 1977, '03:30', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (125, 'Passenger', 'Terrapin Station', 'Progressive', 'Phil Lesh, Peter Monk', 'Bob Weir, Donna Godchaux', 1977, '02:48', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (126, 'Samson & Delilah', 'Terrapin Station', 'Progressive', 'Bob Weir', 'Bob Weir, Donna Godchaux', 1977, '03:30', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (127, 'Sunrise', 'Terrapin Station', 'Progressive', 'Donna Godchaux', 'Donna Godchaux', 1977, '04:05', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (128, 'Terrapin Station Medley', 'Terrapin Station', 'Progressive', 'Grateful Dead, Robert Hunter', 'Jerry Garcia, The English Choral', 1977, '16:23', 'Keith Godchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (129, 'Good Lovin''', 'Shakedown Street', 'Pop', 'Rud Clark, Arthur Resnick', 'Bob Weir', 1978, '04:51', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (130, 'France', 'Shakedown Street', 'Pop', 'Mickey hart, Robert Hunter, Bob Weir', 'Bob Weir, Donna Godchaux', 1978, '04:03', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (131, 'Shakedown Street', 'Shakedown Street', 'Pop', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1978, '04:59', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (132, 'Serengetti', 'Shakedown Street', 'Pop', 'Mickey Hart, Bill Kreutzmann', 'Instrumental', 1978, '01:59', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (133, 'Fire on the Mountain', 'Shakedown Street', 'Pop', 'Mickey Hart, Bill Kreutzmann', 'Jerry Garcia', 1978, '03:46', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (134, 'I Need a Miracle', 'Shakedown Street', 'Pop', 'John Perry Barlow, Bob Weir', 'Bob Weir', 1978, '03:36', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (135, 'From the Heart of Me', 'Shakedown Street', 'Pop', 'Donna Godchaux', 'Donna Godchaux', 1978, '03:23', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (136, 'Stagger Lee', 'Shakedown Street', 'Pop', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1978, '03:35', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (137, 'All New Minglewood Blues', 'Shakedown Street', 'Pop', 'Noah Lewis', 'Bob Weir', 1978, '04:12', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (138, 'If I Had the World to Give', 'Shakedown Street', 'Pop', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1978, '04:50', 'Keith Goddchaux');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (139, 'Alabama Getaway', 'Go to Heaven', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1980, '03:36', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (140, 'Far From Me', 'Go to Heaven', 'Blues', 'Brent Mydland', 'Brent Mydland', 1980, '03:40', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (141, 'Althea', 'Go to Heaven', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1980, '06:51', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (142, 'Feel Like a Stranger', 'Go to Heaven', 'Blues', 'Bob Weir, John Perry Barlow', 'Bob Weir', 1980, '05:07', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (143, 'Lost Sailor', 'Go to Heaven', 'Blues', 'Bob Weir, John Perry Barlow', 'Bob Weir', 1980, '05:54', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (144, 'Saint of Circumstance', 'Go to Heaven', 'Blues', 'Bob Weir, John Perry Barlow', 'Bob Weir', 1980, '05:40', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (145, 'Antwerp''s Placebo (The Plumber)', 'Go to Heaven', 'Blues', 'Mickey Hart, Bill Kreutzmann', 'Instrumental', 1980, '0:38', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (146, 'Easy to Love You', 'Go to Heaven', 'Blues', 'Brent Mydland, John Perry Barlow', 'Brent Mydland', 1980, '03:40', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (147, 'Don''t Ease Me In', 'Go to Heaven', 'Blues', 'Grateful Dead', 'Jerry Garcia', 1980, '03:13', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (148, 'Dire Wolf', 'Reckoning', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '03:20', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (149, 'The Race Is On', 'Reckoning', 'Jam', 'Don Rollins', 'NULL', 1981, '02:58', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (150, 'Oh Babe, It Ain''t No Lie', 'Reckoning', 'Jam', 'Elizabeth Cotten', 'NULL', 1981, '06:28', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (151, 'It Must Have Been the Roses', 'Reckoning', 'Jam', 'Robert Hunter', 'NULL', 1981, '06:56', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (152, 'Dark Hollow', 'Reckoning', 'Jam', 'Bill Browning', 'NULL', 1981, '03:49', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (153, 'China Doll', 'Reckoning', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '05:22', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (154, 'Been All Around This World', 'Reckoning', 'Jam', 'Grateful Dead', 'NULL', 1981, '04:31', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (155, 'Monkey and the Engineer', 'Reckoning', 'Jam', 'Jesse Fuller', 'NULL', 1981, '02:37', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (156, 'Jack-A-Roe', 'Reckoning', 'Jam', 'Grateful Dead', 'NULL', 1981, '04:05', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (157, 'Deep Elem Blues', 'Reckoning', 'Jam', 'Grateful Dead', 'NULL', 1981, '04:51', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (158, 'Cassidy', 'Reckoning', 'Jam', 'Bob Weir, John Perry Barlow', 'NULL', 1981, '04:38', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (159, 'To Lay Me Down', 'Reckoning', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '08:59', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (160, 'Rosalie McFall', 'Reckoning', 'Jam', 'Charlie Monroe', 'NULL', 1981, '02:54', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (161, 'On The Road Again', 'Reckoning', 'Jam', 'Grateful Dead', 'NULL', 1981, '03:15', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (162, 'Bird Song', 'Reckoning', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '07:34', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (163, 'Ripple', 'Reckoning', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '04:38', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (164, 'Samson and Delilah', 'Dead Set', 'Jam', 'Bob Weir', 'NULL', 1981, '05:02', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (165, 'Friend of the Devil', 'Dead Set', 'Jam', 'Jerry Garcia, John Dawson, Robert Hunter', 'NULL', 1981, '07:28', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (166, 'New Minglewood Blues', 'Dead Set', 'Jam', 'Grateful Dead', 'NULL', 1981, '04:41', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (167, 'Deal', 'Dead Set', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '04:36', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (168, 'Candyman', 'Dead Set', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '07:15', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (169, 'Little Red Rooster', 'Dead Set', 'Jam', 'Willie Dixon', 'NULL', 1981, '04:31', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (170, 'Loser', 'Dead Set', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '05:45', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (171, 'Passenger', 'Dead Set', 'Jam', 'Phil Lesh, Peter Monk', 'NULL', 1981, '03:21', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (172, 'Feel Like a Stranger', 'Dead Set', 'Jam', 'Bob Weir, John Perry Barlow', 'NULL', 1981, '05:41', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (173, 'Franklin''s Tower', 'Dead Set', 'Jam', 'Jerry Garcia, Bill Kreutzmann, Robert Hunter', 'NULL', 1981, '05:22', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (174, 'Rhythm Devils', 'Dead Set', 'Jam', 'Mickey Hart, Bill Kreutzmann', 'NULL', 1981, '04:02', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (175, 'Space', 'Dead Set', 'Jam', 'Phil Lesh, Brent Mydland, Mickey Hart, Bill Kreutxmann', 'NULL', 1981, '02:29', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (176, 'Fire on the Mountain', 'Dead Set', 'Jam', 'Mickey hart, Robert Hunter', 'NULL', 1981, '06:30', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (177, 'Greatest Story Ever Told', 'Dead Set', 'Jam', 'Mickey Hart, Bob Weir, Robert Hunter', 'NULL', 1981, '04:04', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (178, 'Brokedown Palace', 'Dead Set', 'Jam', 'Jerry Garcia, Robert Hunter', 'NULL', 1981, '05:42', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (179, 'Touch of Grey', 'In the Dark', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1987, '05:47', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (180, 'Hell in a Bucket', 'In the Dark', 'Blues', 'John Perry Barlow, Bob Weir, Brent Mydland', 'Bob Weir', 1987, '05:35', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (181, 'When Push Comes to Shove', 'In the Dark', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1987, '04:05', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (182, 'West L.A. Fadeaway', 'In the Dark', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1987, '06:39', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (183, 'Tons of Steel', 'In the Dark', 'Blues', 'Brent Mydland', 'Brent Mydland', 1987, '05:15', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (184, 'Throwing Stones', 'In the Dark', 'Blues', 'John Perry Barlow, Bob Weir', 'Bob Weir', 1987, '07:18', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (185, 'Black Muddy River', 'In the Dark', 'Blues', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1987, '05:58', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (186, 'Slow Train', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '04:54', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (187, 'I Want You', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '03:59', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (188, 'Gotta Serve Somebody', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '05:42', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (189, 'Queen Jane Approximately', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '06:30', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (190, 'Joey', 'Dylan & the Dead', 'Gospel', 'Bob Dylan, Jacques Levy', 'NULL', 1989, '09:10', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (191, 'All Along the Watchtower', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '06:17', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (192, 'Knockin'' on Heaven''s Door', 'Dylan & the Dead', 'Gospel', 'Bob Dylan', 'NULL', 1989, '06:51', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (193, 'Foolish Heart', 'Built to Last', 'Pop', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1989, '05:10', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (194, 'Just a Little Light', 'Built to Last', 'Pop', 'John Perry Barlow, Brent Mydland', 'Brent Mydland', 1989, '04:42', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (195, 'Built to Last', 'Built to Last', 'Pop', 'Jerry Garcia, Robert Hunter', 'Jerry Garcia', 1989, '05:03', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (196, 'Blow Away', 'Built to Last', 'Pop', 'John Perry Barlow, Brent Mydland', 'Brent Mydland', 1989, '06:09', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (197, 'Victim or the Crime', 'Built to Last', 'Pop', 'Bob Weir', 'Bob Weir', 1989, '07:33', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (198, 'We Can''t Run', 'Built to Last', 'Pop', 'Brent Mydland', 'Brent Mydland', 1989, '05:30', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (199, 'Standing on the Moon', 'Built to Last', 'Pop', 'Jerry Garcia', 'Jerry Garcia', 1989, '05:20', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (200, 'Picasso Moon', 'Built to Last', 'Pop', 'Bob Weir', 'John Perry Barlow,  Bob Bralove', 1989, '06:40', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (201, 'I Will Take You Home', 'Built to Last', 'Pop', 'Brent Mydland', 'Brent Mydland', 1989, '03:45', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (202, 'Feel Like a Stranger', 'Without a Net', 'Jam', 'John Perry Barlow, Bob Weir', 'NULL', 1990, '07:32', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (203, 'Mississippi Half-Step Uptown Toodeloo', 'Without a Net', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1990, '08:00', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (204, 'Walkin'' Blues', 'Without a Net', 'Jam', 'Robert Johnson, Bob Weir', 'NULL', 1990, '05:44', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (205, 'Althea', 'Without a Net', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1990, '06:55', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (206, 'Cassidy', 'Without a Net', 'Jam', 'John Perry Barlow, Bob Weir', 'NULL', 1990, '06:36', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (207, 'Bird Song', 'Without a Net', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1990, '12:57', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (208, 'Let It Grow', 'Without a Net', 'Jam', 'John Perry Barlow, Bob Weir', 'NULL', 1990, '11:55', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (209, 'China Cat Sunflower/I Know You Rider', 'Without a Net', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1990, '10:24', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (210, 'Looks Like Rain', 'Without a Net', 'Jam', 'John Perry Barlow, Bob Weir', 'NULL', 1990, '08:04', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (211, 'Eyes of the World', 'Without a Net', 'Jam', 'Robert Hunter, Jerry Garcia', 'NULL', 1990, '16:14', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (212, 'Victim or the Crime', 'Without a Net', 'Jam', 'Gerrit Graham, Bob Weir', 'NULL', 1990, '08:04', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (213, 'Help on the Way/Slipknot/Franklin''s Tower', 'Without a Net', 'Jam', 'Grateful Dead, Robert Hunter', 'NULL', 1990, '19:07', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (214, 'One More Saturday Night', 'Without a Net', 'Jam', 'Bob Weir', 'NULL', 1990, '04:51', 'Brent Mydland');
INSERT INTO songs (song_id, song_name, album, genre, writer, lead_singer, release_year, duration, keyboardist) VALUES (215, 'Dear Mr. Fantasy', 'Without a Net', 'Jam', 'Jim Capaldi, Steve Winwood, Chris Wood', 'NULL', 1990, '05:44', 'Brent Mydland');